name: "Wayne Ye"
title: Wayne's Geek Life
title_separator: "-"
email: hi@wayneye.me
keyword: "Wayne Ye,WayneYe.me,Geek,Programming,C#,ASP.NET,GO,Python,Ruby,Rails,Cucumber,JavaScript,nodejs,HTML5,SOLID,AWS,Microservices"
description: "I am a software engineer, technical lead and also a geek, I've immersed in software/web development for 14 years, I hack using these languages: Python, Golang, JavaScript/nodejs, Ruby/RoR, C#. I am an AWS Certified Solutions Architect (2017-2019), PMP and CodeProject MVP."
url: "https://wayneye.me"
SEOTitle: Wayne's Geek Life
locale: "en-US"
header-img: assets/images/Banner.jpg
#head_scripts:
  #- https://code.jquery.com/jquery-3.2.1.min.js
  #- /assets/js/your-custom-head-script.js
baseurl: ""
#logo: "assets/images/88x88.png"
github: [metadata]
repository: WayneYe/wayneye.github.io
excerpt_separator: <!--more-->

author:
  name             : "Wayne Ye"
  avatar           : "assets/images/me.jpg"
  bio              : "Whatever is worth doing is worth doing well!"
  location         : "San Francisco"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:hi@wayneye.me
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://wayneye.me"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/wayneye"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WayneYe/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/wayneye"

twitter:
  username: "wayneye"

#theme: jekyll-theme-hacker
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"


plugins:
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-archives
  - jemoji
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: single
      classes: wide
      author_profile: true
      # read_time: true 不准!中文支持不好
      comments: true
      share: true
      related: true
      toc: true
      #toc_label: "Table of Contents"
      toc_icon: "cog"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: "assets/img"
    values:
      image: true

comments:
  provider: "disqus"
  disqus:
    shortname: "wayneye"
  #provider: "facebook"
  #facebook:
    #appid: 374223339969060
    #num_posts: 5 # 5 (default)
    #colorscheme: light # "light" (default), "dark"

# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
   - categories
   - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# SEO Stuff
google:
  #search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  #instant_search         : # false (default), true
# SEO Related
#google_site_verification :
#bing_site_verification   :
#yandex_site_verification :
#naver_site_verification  :

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:hi@wayneye.me
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://wayneye.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/wayneye"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/WayneYeDotCom"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/WayneYe/"
